In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv("matrix.csv")

In [4]:
df

,Unnamed: 0,rs144366698,rs200391621,rs78888200,rs200049935,rs182808734,rs147783986,rs202082800,rs185745570,rs151231161,...,rs6010062,rs186386126,rs73174436,rs6010073,rs181024981,rs180882000,rs147614277,rs192355741,rs191731586,Population code
0,HG00096,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,GBR
1,HG00097,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,GBR
2,HG00099,0,0,1,0,0,1,0,0,0,...,1,0,0,2,0,0,1,0,0,GBR
3,HG00100,0,0,2,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,GBR
4,HG00101,0,0,1,0,0,1,0,0,0,...,2,0,0,1,0,0,0,0,0,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,NA20816,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,TSI
1088,NA20818,0,0,0,0,0,0,0,0,0,...,2,0,0,1,0,0,0,0,0,TSI
1089,NA20819,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TSI
1090,NA20826,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TSI
1091,NA20828,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TSI

In [5]:
df["Population code"].value_counts()

Population code
CHS    100
TSI     98
CHB     97
LWK     97
FIN     93
GBR     89
JPT     89
YRI     88
CEU     85
MXL     66
ASW     61
CLM     60
PUR     55
IBS     14
Name: count, dtype: int64

In [8]:
matrix = df.drop(["Population code","Unnamed: 0"],axis=1)

In [26]:
pca = PCA(n_components=2)
pca.fit(matrix)
print(pca.singular_values v c x cfds_)
df_pca = pca.transform(matrix)
print(df_pca.shape)

[188.93732058 152.99536559]
(1092, 2)

In [27]:
df_pca = pd.DataFrame(df_pca)
df_pca["pcode"] = df["Population code"]

In [29]:
from sklearn.preprocessing import LabelEncoder
lc = LabelEncoder()
df_pca["pcode"] = lc.fit_transform(df_pca["pcode"])
df_pca

             0         1  pcode
0     0.312827  5.354349      6
1    -0.679403  6.183329      6
2    -0.420710  5.266720      6
3    -0.805419  5.965095      6
4    -0.771385  4.332076      6
...        ...       ...    ...
1087  0.647431  5.090230     12
1088 -1.226520  6.273755     12
1089  0.200440  4.437550     12
1090  0.119733  4.959937     12
1091 -0.286888  3.466173     12

[1092 rows x 3 columns]

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df_pca.drop(["pcode"],axis=1),df_pca["pcode"])

In [33]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_hat = lr.predict(X_test)
cls = classification_report(y_hat,y_test)
print(cls)

              precision    recall  f1-score   support

           0       0.50      0.58      0.54        12
           1       0.00      0.00      0.00         1
           2       0.37      0.38      0.37        29
           3       0.45      0.37      0.41        38
           4       0.12      0.40      0.19         5
           5       0.46      0.41      0.43        32
           6       0.38      0.31      0.34        26
           7       0.00      0.00      0.00         0
           8       0.20      0.25      0.22        20
           9       0.46      0.63      0.53        19
          10       0.86      0.32      0.46        19
          11       0.30      0.50      0.37         6
          12       0.50      0.26      0.35        34
          13       0.86      0.56      0.68        32

    accuracy                           0.40       273
   macro avg       0.39      0.35      0.35       273
weighted avg       0.49      0.40      0.42       273

/Users/sujaykumar/miniconda3/envs/pytorch/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/sujaykumar/miniconda3/envs/pytorch/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/pytorch/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sujaykumar/miniconda3/envs/pytorch/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [55]:
result = []

In [98]:
n_comps = 50
pca = PCA(n_components=n_comps)
pca.fit(matrix)
print(pca.singular_values_)
df_pca = pca.transform(matrix)
print(df_pca.shape)
df_pca = pd.DataFrame(df_pca)
df_pca["pcode"] = df["Population code"]
from sklearn.preprocessing import LabelEncoder
lc = LabelEncoder()
df_pca["pcode"] = lc.fit_transform(df_pca["pcode"])
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df_pca.drop(["pcode"],axis=1),df_pca["pcode"])
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_hat = lr.predict(X_test)
cls = classification_report(y_hat,y_test)
import re

averages = re.findall(r'macro avg\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)', cls)
macro_avg = [float(val) for val in averages[0]]
averages = re.findall(r'weighted avg\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)', cls)
weighted_avg = [float(val) for val in averages[0]]
x = [n_comps,macro_avg[0],macro_avg[1],macro_avg[2],weighted_avg[0],weighted_avg[1],weighted_avg[2]]
# print(cls)

[188.93732058 152.99536559  75.47602422  54.24626987  52.07644638
  50.61567449  49.25514288  48.5591286   46.9651995   46.47645049
  45.59437691  45.43647085  45.05220049  44.64900771  43.93136738
  43.2391918   42.87280066  42.46106526  41.8896949   41.75604017
  41.33386338  41.24298953  40.92446375  40.62398079  40.44987547
  40.35784354  40.0328153   39.7052473   39.41307524  39.29883349
  39.07636351  38.90292631  38.74450368  38.68669706  38.37338862
  38.30630756  38.16940155  37.76846336  37.69105828  37.56566369
  37.20861178  37.09324197  36.91311964  36.903663    36.43260335
  36.34220662  36.30084538  36.11343363  36.00027756  35.77769346]
(1092, 50)

/Users/sujaykumar/miniconda3/envs/pytorch/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [99]:
result.append(x)

In [100]:
pd.DataFrame(result,columns=["PCA_Components","macro_avg_precision","macro_avg_recall","macro_avg_f1_score","weighted_avg_precison","weighted_avg_recall","weighted_avg_f1_score"])

,PCA_Components,macro_avg_precision,macro_avg_recall,macro_avg_f1_score,weighted_avg_precison,weighted_avg_recall,weighted_avg_f1_score
0,2,0.38,0.32,0.33,0.55,0.38,0.43
1,3,0.40,0.38,0.38,0.51,0.43,0.45
2,4,0.40,0.41,0.35,0.57,0.40,0.44
3,6,0.40,0.40,0.39,0.50,0.42,0.44
4,8,0.42,0.41,0.40,0.49,0.44,0.45
5,10,0.47,0.46,0.46,0.55,0.51,0.52
6,12,0.47,0.47,0.46,0.55,0.51,0.52
7,14,0.49,0.50,0.48,0.57,0.52,0.53
8,16,0.48,0.48,0.48,0.54,0.52,0.53
9,18,0.53,0.58,0.54,0.57,0.54,0.55
10,20,0.51,0.49,0.49,0.56,0.53,0.54
11,22,0.58,0.54,0.52,0.61,0.55,0.55
12,24,0.52,0.53,0.52,0.57,0.57,0.56
13,28,0.48,0.50,0.48,0.53,0.51,0.52
14,50,0.53,0.53,0.53,0.59,0.58,0.58

In [102]:
result = pd.DataFrame(result,columns=["PCA_Components","macro_avg_precision","macro_avg_recall","macro_avg_f1_score","weighted_avg_precison","weighted_avg_recall","weighted_avg_f1_score"])
result.to_csv("results.csv")